version: "3.9"

services:
  exam-db:
    container_name: exam-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5445:5432"
    volumes:
      - exam-db-postgres-volume:/var/lib/postgresql/data

volumes:
  exam-db-postgres-volume:
